//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidadorIngresos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://miportafoliouat.transunion.co/ValidadorIEWS/services/ValidadorIEWS", ConfigurationName="ValidadorIngresos.ValidadorWS")]
    public interface ValidadorWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ValidadorIngresos.consultaValidadorResponse> consultaValidadorAsync(ValidadorIngresos.consultaValidadorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.validador.ws.co")]
    public partial class ParametersValidadorDTO
    {
        
        private string autorizacionField;
        
        private string idProductoField;
        
        private string numeroIdentificacionField;
        
        private string salarioReportadoField;
        
        private string tipoIdentificacionField;
        
        private string usuarioIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string autorizacion
        {
            get
            {
                return this.autorizacionField;
            }
            set
            {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string idProducto
        {
            get
            {
                return this.idProductoField;
            }
            set
            {
                this.idProductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroIdentificacion
        {
            get
            {
                return this.numeroIdentificacionField;
            }
            set
            {
                this.numeroIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string salarioReportado
        {
            get
            {
                return this.salarioReportadoField;
            }
            set
            {
                this.salarioReportadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string usuarioId
        {
            get
            {
                return this.usuarioIdField;
            }
            set
            {
                this.usuarioIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaValidador", WrapperNamespace="http://ws.validador.ws.co", IsWrapped=true)]
    public partial class consultaValidadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ValidadorIngresos.ParametersValidadorDTO parametrosValidador;
        
        public consultaValidadorRequest()
        {
        }
        
        public consultaValidadorRequest(ValidadorIngresos.ParametersValidadorDTO parametrosValidador)
        {
            this.parametrosValidador = parametrosValidador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaValidadorResponse", WrapperNamespace="https://miportafoliouat.transunion.co/ValidadorIEWS/services/ValidadorIEWS", IsWrapped=true)]
    public partial class consultaValidadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultaValidadorReturn;
        
        public consultaValidadorResponse()
        {
        }
        
        public consultaValidadorResponse(string consultaValidadorReturn)
        {
            this.consultaValidadorReturn = consultaValidadorReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ValidadorWSChannel : ValidadorIngresos.ValidadorWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ValidadorWSClient : System.ServiceModel.ClientBase<ValidadorIngresos.ValidadorWS>, ValidadorIngresos.ValidadorWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ValidadorWSClient() : 
                base(ValidadorWSClient.GetDefaultBinding(), ValidadorWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ValidadorIEWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidadorWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ValidadorWSClient.GetBindingForEndpoint(endpointConfiguration), ValidadorWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidadorWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ValidadorWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidadorWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ValidadorWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidadorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidadorIngresos.consultaValidadorResponse> ValidadorIngresos.ValidadorWS.consultaValidadorAsync(ValidadorIngresos.consultaValidadorRequest request)
        {
            return base.Channel.consultaValidadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidadorIngresos.consultaValidadorResponse> consultaValidadorAsync(ValidadorIngresos.ParametersValidadorDTO parametrosValidador)
        {
            ValidadorIngresos.consultaValidadorRequest inValue = new ValidadorIngresos.consultaValidadorRequest();
            inValue.parametrosValidador = parametrosValidador;
            return ((ValidadorIngresos.ValidadorWS)(this)).consultaValidadorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidadorIEWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidadorIEWS))
            {
                return new System.ServiceModel.EndpointAddress("https://miportafoliouat.transunion.co/ValidadorIEWS/services/ValidadorIEWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ValidadorWSClient.GetBindingForEndpoint(EndpointConfiguration.ValidadorIEWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ValidadorWSClient.GetEndpointAddress(EndpointConfiguration.ValidadorIEWS);
        }
        
        public enum EndpointConfiguration
        {
            
            ValidadorIEWS,
        }
    }
}
